import type { Publication } from './types'

// Generated by scripts/extract-publications.mjs from the source page. Do not hand-edit.
export const publications: Publication[] = [
  {
    "n": 1,
    "text": "Abhyankar A, Abizaid A, Chamié D, Rathod M. Comparison of neointimal coverage between ultrathin biodegradable polymer‐coated sirolimus‐eluting stents and durable polymer‐coated everolimus‐eluting stents: 6 months optical coherence tomography follow‐up from the TAXCO study. Catheter Cardiovasc Interv. 2020. 10.1002/ccd.28833."
  },
  {
    "n": 2,
    "text": "Abhyankar A, Abizaid LC, Chamie D. Early vascular responses after ultrathin strut biodegradable polymer-coated sirolimus-eluting stent implantation: SiBi OCT study. EuroPCR 2019; 03-May, 2019; Paris.https://abstractbook.pcronline.com/export/pdf/id/130564 [Abstract]"
  },
  {
    "n": 3,
    "text": "Twelve-month comparative analysis of clinical outcomes using biodegradable polymer-coated everolimus-eluting stents versus durable polymer-coated everolimus-eluting stents in all-comers patients. Abhyankar A, Sandhu MS, Polavarapu RS. Indian Heart J. 2019, Available online 3 May 2019 (https://doi.org/10.1016/j.ihj.2019.04.013)."
  },
  {
    "n": 4,
    "text": "Evaluation of vascular response and healing after implantation of tetrilimus everolimus-eluting coronary stent by optical coherence tomography (EVER-OCT): 3- and 6-Month Serial Analysis. Kaul U, Abhaichand R, Abhyankar A, et al. J Am Coll Cardiol. Volume 73, Issue 15 Supplement, April 2019 (doi: 10.1016/j.jacc.2019.03.027). [Abstract]"
  },
  {
    "n": 5,
    "text": "Impact of diabetes, hypertension and smoking on magnitude of improvement in LVEF in patients with anterior wall ST elevation myocardial infarction (STEMI) treated with primary PCI. Rathod M, Patel G, Abhyankar A. Indian Heart J. Volume 70, Supplement 2, November 2018, Page S33 (https://doi.org/10.1016/j.ihj.2018.10.099)."
  },
  {
    "n": 6,
    "text": "Seven-year clinical outcomes in patients undergoing percutaneous coronary intervention with biodegradable polymer coated sirolimus-eluting stent: Results from a single-center real-world experience. Abhyankar A, Kaul U, Sinha SK. Published online 26 May 2018. Indian Heart J. 2018 Dec;70 Suppl 3:S280-S284 (doi: 10.1016/j.ihj.2018.05.014)."
  },
  {
    "n": 7,
    "text": "Interventional Cardiology Practices in India. Indian Stents: Gaps Are Narrowing. Abhyankar A, Kaul U. In: Deb PK. CSI Textbook of Cardiology: The Indian Perspective. JAYPEE BROTHERS Medical Publishers (P) Ltd., India. 2018. Chapter 37, Page no. 489-513."
  },
  {
    "n": 8,
    "text": "Comparison of neointimal coverage between ultrathin biodegradable polymer-coated sirolimus-eluting stents and durable polymer-coated everolimus-eluting stents: six-month OCT follow-up from the TAXCO study. Abhyankar A, Abizaid LC, Chamié D, Rathod M. EuroPCR 2018 programme, 22-25 May 2018, Paris (Euro18A-POS141) and published on 15 May 2018. (https://abstractbook.pcronline.com/export/pdf/id/100317) [Abstract]"
  },
  {
    "n": 9,
    "text": "Twelve-month comparative analysis of clinical outcomes using biodegradable polymer-coated everolimus-eluting stents vs. durable polymer-coated everolimus-eluting stents in all-comer patients. Abhyankar A, Sandhu MS, Polavarapu RS. EuroPCR 2018 programme, 22-25 May 2018, Paris (Euro18A-POS140) and published on 15 May 2018. (https://abstractbook.pcronline.com/export/pdf/id/100316) [Abstract]"
  },
  {
    "n": 10,
    "text": "Seven-year clinical outcomes in patients undergoing PCI with biodegradable polymer-coated sirolimus-eluting stent: results from a single-centre real-world experience. Abhyankar A, Kaul U, Sinha SK. EuroPCR 2018 programme, 22-25 May 2018, Paris (Euro18A-POS144) and published on 15 May 2018. (https://abstractbook.pcronline.com/export/pdf/id/100320) [Abstract]"
  },
  {
    "n": 11,
    "text": "Clinical Outcomes in 995 Unselected Real-world Patients Treated With an Ultra-thin Biodegradable Polymer-Coated Sirolimus-Eluting Stent: 12 Months Results from the FLEX-Registry. Lemos PA, Chandwani P, Saxena S, Ramachandran P, Abhyankar A, Campos CM, Marchini JF, Galon MZ, Verma P, Sandhu MS, Parikh N, Bhupali A, Jain S, Prajapati J. BMJ Open. 2016 Feb 17;6(2):e010028. doi: 10.1136/bmjopen-2015-010028."
  },
  {
    "n": 12,
    "text": "Comparison of Clinical Outcomes Following Single versus Multivessel Percutaneous Coronary Intervention Using Biodegradable Polymer Coated Sirolimus-Eluting Stent in an All-comers Patient Population. Chandwani P, Verma P, Saxena S, Ramachandran PK, Abhyankar A, Sandhu MS, Parikh N, Bhupali A, Jain S, Prajapati J. Cardiovasc Hematol Agents Med Chem. 2016;14(1):39-48"
  },
  {
    "n": 13,
    "text": "Clinical Outcomes in 995 Unselected Real-world Patients Treated With an Ultra-thin Biodegradable Polymer-Coated Sirolimus-Eluting Stent: 12 Months Results from the FLEX-Registry. Lemos PA, Chandwani P, Saxena S, Ramachandran P, Abhyankar A, Campos CM, Marchini JF, Galon MZ, Verma P, Sandhu MS, Parikh N, Bhupali A, Jain S, Prajapati J. Catheter Cardiovasc Interv. 2016;87(S2):S131 (C-018). DOI 10.1002/ccd. [Abstract]"
  },
  {
    "n": 14,
    "text": "Biodegradable polymer-based, ultra-thin, sirolimus-eluting coronary stents have favorable outcomes in unselected 'real-world' patients with coronary artery lesions irrespective of implanted stent size: The Size-FLEX registry. Chandwani P, Saxena S, Ramachandran P, Abhyankar A, Verma P, Sandhu MS, Parikh N, Bhupali A, Jain S, Prajapati J. Catheter Cardiovasc Interv. 2016;87(S2):S131 (C-019). DOI 10.1002/ccd. [Abstract]"
  },
  {
    "n": 15,
    "text": "Immediate and 1-Year Outcomes following Sirolimus-Eluting Stent Implantation in Elderly Patients: An Indian Experience. Sandhu MS, Jain S, Chandwani P, Saxena S, Parikh N, Abhyankar A, Verma P, Ramachandran P, Bhupali A, Prajapati J. Catheter Cardiovasc Interv. 2016;87(S2):S132 (C-020). DOI 10.1002/ccd. [Abstract]"
  },
  {
    "n": 16,
    "text": "A Propensity Matched Real-world Evaluation of Ultra-thin Biodegradable Polymer Coated Sirolimus-eluting Stents in Diabetic and Non-Diabetic Patients with Coronary Artery Disease – One-year Clinical Outcomes of the DiaFLEX Registry. Prajapati J, Jain S, Saxena S, Chandwani P, Ramachandran P, Abhyankar A, Verma P, Parikh N, Sandhu MS, Bhupali A. Catheter Cardiovasc Interv. 2016;87(S2):S134 (C-070). DOI 10.1002/ccd. [Abstract]"
  },
  {
    "n": 17,
    "text": "Clinical Outcomes in 995 Unselected Real-world Patients Treated With an Ultra-thin Biodegradable Polymer-Coated Sirolimus-Eluting Stent: 12 Months Results from the FLEX-Registry. Lemos PA, Chandwani P, Saxena S, Ramachandran P, Abhyankar A, Campos CM, Marchini JF, Galon MZ, Verma P, Sandhu MS, Parikh N, Bhupali A, Jain S, Prajapati J. EuroIntervention. Abstracts EuroPCR 2016. May 2016. (Euro16A-OP0324) [Abstract]"
  },
  {
    "n": 18,
    "text": "Paclitaxel-Eluting versus Everolimus-Eluting Coronary Stents in Diabetes. Kaul U, Bangalore S, Seth A, Arambam P, Abhaychand RK, Patel TM, Banker D, Abhyankar A, Mullasari AS, Shah S, Jain R, Kumar PR, Bahuleyan CG; TUXEDO–India Investigators. N Engl J Med. 2015 Oct 29;373(18):1709-19."
  },
  {
    "n": 19,
    "text": "Real-world experience with ultra-thin biodegradable polymer coated sirolimus-eluting coronary stent: Six-month clinical outcomes of FLEX-Registry. A. Abhyankar , P. Chandwani, S. Saxena, P. Kumar, P. Verma, M.S. Sandhu, N. Parikh, A. Bhupali, S. Jain, J. Prajapati. European Heart Journal. Volume 36, Issue suppl 1, 1 August 2015 (Abstract P4713). [Abstract]"
  },
  {
    "n": 20,
    "text": "Real world use of ultra-thin sirolimus-eluting stent with biodegradable polymers. 9-month results from the FLEX-registry. Lemos PA, Chandwani P, Saxena S, Ramachandran P, Abhyankar A, Campos CM, Marchini JF, Galon MZ, Verma P, Sandhu MS, Parikh N, Bhupali A, Jain S, Prajapati J. J Am Coll Cardiol. 2015;66(15_S): doi:10.1016/j.jacc.2015.08.499 (Abstract No. TCT-483). [Abstract]"
  },
  {
    "n": 21,
    "text": "Clinical Outcomes of Biodegradable-Polymer Coated Sirolimus-Eluting Stent in Unselected Patients with Long Coronary Lesions: LONG-FLEX Registry. Prakash Chandwani, Puneet Verma, Sudheer Saxena, Atul Abhyankar, Manjinder Singh Sandhu, Nikhil Parikh, Jayesh Prajapati, Sharad Jain, Ashok N. Bhupali, Padma Kumar Ramachandran, Arohi Sarang, Ashok Thakkar. J Am Coll Cardiol. 2015;66(15_S):. doi:10.1016/j.jacc.2015.08.1041 (Abstract No. TCT-571). [Abstract]"
  },
  {
    "n": 22,
    "text": "Clinical performance of the cobalt-chromium biodegradable polymer coated sirolimus-eluting stent in an unselected real-world population. P. Chandwani, A. D. Abhyankar, J. S. Prajapati, S. C. Porwal, and A. S. Thakkar. Int J Clin Med, vol. 5, no., pp. 206-215, 2014."
  },
  {
    "n": 23,
    "text": "Clinical performance of the cobalt-chromium biodegradable polymer coated sirolimus-eluting stent in an unselected real-world population (S-CORE Registry). Sanjay Porwal, Prakash Chandwani, Atul Abhyankar, Jayesh Prajapati, Ashok Thakkar. Catheterization and Cardiovascular Interventions. Volume 83, Issue Supplement S1, pages S1–S247 (S180), 1 May 2014 (C-079). [Abstract]"
  },
  {
    "n": 24,
    "text": "Comparative conformability of two cobalt-chromium stents with different stents design and strut thickness. Abhyankar A., Chodvadiya P., Shah P., Virupil M., Thakkar A. EuroIntervention. EuroPCR Abstracts and Posters 2014. May 2014. (Euro14A-POS078). [Abstract]"
  },
  {
    "n": 25,
    "text": "A case of type variant Kounis syndrome with Samter-Beer triad. Prajapati JS, Virpariya KM, Thakkar AS, Abhyankar AD. World J Cardiol. 2013 Apr 26;5(4):112-4."
  },
  {
    "n": 26,
    "text": "Early vascular healing with biodegradable polymer coated sirolimus-eluting coronary stent implantation: assessed by optical coherence tomography results at 4-month follow-up. Abhyankar A, Prajapati J, Reddy S, Reddy S. Minerva Cardioangiol. 2013 Jun;61(3):313-22."
  },
  {
    "n": 27,
    "text": "Systemic exposure of sirolimus after coronary stent implantation in patients with de novo coronary lesions: Supralimus-Core® pharmacokinetic study. Thakkar AS, Abhyankar AD, Dani SI, Banker DN, Singh PI, Parmar SA, Mehta AA. Indian Heart J. 2012 May-Jun;64(3):273-9."
  },
  {
    "n": 28,
    "text": "In vivo assessment of stent recoil of biodegradable polymer-coated cobalt-chromium sirolimus-eluting coronary stent system. Abhyankar AD, Thakkar AS. Indian Heart J. 2012 Nov-Dec;64(6):541-6."
  },
  {
    "n": 29,
    "text": "Use of enoxaparin in emergency room for improving outcomes of primary percutaneous coronary interventions for acute myocardial infarction. Abhyankar AD, Pothiawala SE, Kazi GJ, Jha MJ, Petrolwala M. Indian Heart J; 2008 Jan-Feb;60(1):39-44."
  },
  {
    "n": 30,
    "text": "Multivessel stenting in patients with very low ejection fraction. Abhyankar AD, Riyami AA, Suleiman KJ, Shahrabani R, Riyami AM. American Journal of Cardiology: October 2000. [Abstract]"
  },
  {
    "n": 31,
    "text": "Post-infarction ventricular septal defect: percutaneous transvenous temporary closure using a Swan-Ganz catheter. Abhyankar AD, Jagtap PM. Catheter Cardiovasc Interv. 1999 Jun;47(2):208-10."
  },
  {
    "n": 32,
    "text": "Reconstructive angioplasty for diffuse disease. Abhyankar AD, Riyami AA, Shhrabani R, Suleiman KJ, Riyami AM. Indian Heart Journal Dec. 1999. [Abstract]"
  },
  {
    "n": 33,
    "text": "Direct stenting v/s conventional stenting: Early outcomes. Abhyankar AD, Riyami AA, Shahrabani R, Suleiman KJ, Riyami AM. Indian Heart Journal: Dec. 1999. [Abstract]"
  },
  {
    "n": 34,
    "text": "Delayed appearance of coronary artery perforation after stent implantation. Abhyankar AD, England D, Bernstein L, Harris PJ. Cathet Cardiovasc Diagn. 1998 Mar;43(3):311-2."
  },
  {
    "n": 35,
    "text": "Results of stent implantation in small coronary arteries [< 2.7 mm] with complex lesions. Abhyankar AD, Riyami AA, Jagtap PM, Riyami AM. American Journal of Cardiology. 1998. [Abstract]"
  },
  {
    "n": 36,
    "text": "Comparative Elastic Recoil of Palmaz-Schatz and BE stents. Abhyankar AD. Indian Heart Journal. December 1998. [Abstract]"
  },
  {
    "n": 37,
    "text": "Stent Implantation in presence of intracoronary thrombus without adjuvant use of Platelet IIb/IIIa receptor antagonist. Abhyankar AD, Jagtap PM, Shahrabani R, Riyami AA, Suleiman KJ, Riyami AM. Indian Heart Journal. December 1998. [Abstract]"
  },
  {
    "n": 38,
    "text": "Multivessel Stenting: Comparison of Single Vs Staged Approach. Abhyankar AD, Riyami AA, Jagtap PM, Riyami AM. Indian Heart Journal. December 1998. [Abstract]"
  },
  {
    "n": 39,
    "text": "Stent Implantations for Bifurcation Lesions. Abhyankar AD, Riyami AA. Indian Heart Journal. December 1998. [Abstract]"
  },
  {
    "n": 40,
    "text": "Intracoronary Doppler Velocimetry: A New Technique for Physiological Assessment of Coronary Circulation. Abhyankar AD, Bernstein L. Journal of the Association of Physicians of India / v.46 Oct.1998, pp.882-885."
  },
  {
    "n": 41,
    "text": "Stent implantation in severely angulated lesions: safety, efficacy, and morphological remodelling. Abhyankar AD, Luyue G, Bailey BP. Cathet Cardiovasc Diagn. 1997 Mar;40(3):261-4."
  },
  {
    "n": 42,
    "text": "Lack of evidence for improvement in internal mammary graft flow by occlusion of side branch. Abhyankar AD, Mitchell AS, Bernstein L. Cathet Cardiovasc Diagn. 1997 Nov;42(3):291-3."
  },
  {
    "n": 43,
    "text": "Spontaneous regression of post-percutaneous transluminal coronary angioplasty aneurysm. Abhyankar AD, Richmond DR, Bernstein L. Int J Cardiol. 1997 Aug 8;60(3):233-8."
  },
  {
    "n": 44,
    "text": "Warfarin During Pregnancy: Safety for embryopathy and Predisposition to Abortion. Jagtap PM, Abhyankar AD, Pawar NC, Riyami AM. Indian Heart Journal 1997; 49: 658. [Abstract]"
  },
  {
    "n": 45,
    "text": "Angioplasty through a Stent Side-door. Abhyankar A, Gai L, Bailey BP. Int J Cardiol. 1996 Jul 5;55(1):107-10."
  },
  {
    "n": 46,
    "text": "Stent Implantation in Angulated Lesions. Abhyankar AD, Bernstein L, Harris PJ, Bailey BP. Australia and New Zealand Medical Journal 1996. [Abstract]"
  },
  {
    "n": 47,
    "text": "Multiple Coronary-Pulmonary fistulae arising from all three coronary arteries. Abhyankar AD, Mok NS, Helprin G, Pressley L. Int J Cardiol. 1996 Dec 6;57(2):181-3."
  },
  {
    "n": 48,
    "text": "Intracoronary Drug Delivery Systems. Abhyankar AD, Hutt J, Bernstein L. Intercontinental Cardiology 1996."
  },
  {
    "n": 49,
    "text": "Modified Catheter Shapes for unusually wide aortas. Abhyankar AD. Cathet Cardiovasc Diagn. 1996 Nov;39(3):327."
  },
  {
    "n": 50,
    "text": "Reintervention and clinical events after saphenous vein graft angioplasty- a comparison of optimal PTCA v stenting. Abhyankar A, Bernstein L, Harris PJ, Bailey BP. Circulation October 1996. [Abstract]"
  },
  {
    "n": 51,
    "text": "Angioplasty and stenting with adjuvant Abciximab in presence of angiographically detected thrombus. Abhyankar AD, Bernstein L, Harris PJ. Asia Pacific Heart Journal 1996; 5 (2): 103-104."
  },
  {
    "n": 52,
    "text": "Stents for Aorto-Ostial Lesions. Abhyankar AD, Bernstein L. Asia Pacific Interrventional Cardiology - Text Book. December 1996."
  },
  {
    "n": 53,
    "text": "ReoPro for angiographically detected thrombus in relation to PTCA. Abhyankar AD, Bernstein L. Asia Pacific Interventional Cardiology Text Book. December 1996."
  },
  {
    "n": 54,
    "text": "New convenient and fast method of hand mounting Palmaz-Schatz coronary stent. Abhyankar AD, Bailey BP, Harris PJ, Bernstein L. Cathet Cardiovasc Diagn. 1995 Jun;35(2):159-60."
  },
  {
    "n": 55,
    "text": "Transventricular mitral valve dilator: an improved design concept. Kaul A, Bhattacharya S, Borker S, Patwardhan AM, Chaukar AP, Abhyankar AD. J Thorac Cardiovasc Surg. 1995 Sep;110(3):856-9."
  },
  {
    "n": 56,
    "text": "\"Dancing needle sign\" for obtaining access to the femoral artery. Abhyankar AD. Cathet Cardiovasc Diagn. 1995 Aug;35(4):378."
  },
  {
    "n": 57,
    "text": "Outcome of stable coronary dissections following PTCA. Gai L, Abhyankar AD, Bailey BP, Bernstein L, Harris PJ. Australia and New Zealand Medical Journal. 1995 [Abstract]"
  },
  {
    "n": 58,
    "text": "Rotational atherectomy of calcified ostial saphenous vein graft lesion with long term follow-up: a case report. Abhyankar AD, Vaidya KA, Bernstein L. Int J Cardiol. 1995 Nov 10;52(1):11-2."
  },
  {
    "n": 59,
    "text": "Outcome of stable coronary dissections. Gai L, Abhyankar AD, Bernstein L, Harris PJ. Chinese Journal of Cardiology 1995."
  },
  {
    "n": 60,
    "text": "Sion thrombolysis trial-randomised trial of intravenous thrombolysis & primary percutaneous transluminal coronary angioplasty for acute myocardial infarction [AMI]-feasibility phase data of angioplasty limb. Mehta AB, Abhyankar AD. J Assoc Physicians India. 1994 Jan;42(1):43-4."
  },
  {
    "n": 61,
    "text": "Recovery positive exercise stress test: an indication for coronary artery disease. Abhyankar AD, Agrawal AG, Mehta AB. J Assoc Physicians India. 1994 Sep;42(9):700-2."
  },
  {
    "n": 62,
    "text": "Percutaneous transluminal coronary angioplasty (PTCA) in unstable angina. Parikh JA, Abhyankar AD, Kane GR, Chonkar NS, Patwardhan AM, Gandhi MJ. J Assoc Physicians India. 1993 Jan;41(1):9-10."
  },
  {
    "n": 63,
    "text": "Emergency and elective percutaneous balloon mitral valvoplasty by Inoue's technique during pregnancy. Kaneria VK, Kane GR, Abhyankar AD, Patel YS, Pahlajani DB, Mehta AB. Indian Heart Journal 1993: 45;349. [Abstract]"
  },
  {
    "n": 64,
    "text": "Predictors of mortality after angioplasty in acute myocardial infarction. Kane GR, Kaneria VK, Rathod AB, Abhyankar AD, Pahlajani DB, Mehta AB. Indian Heart Journal 1993: 45 ; 422. [Abstract]"
  },
  {
    "n": 65,
    "text": "A preliminary report of a randomised trial of intravenous streptokinase and direct angioplasty in acute myocardial infarction. Mehta AB, Kaneria VK, Kane GR, Abhyankar AD, Pahlajani DB. Indian Heart Journal 1993: 45; 313. [Abstract]"
  },
  {
    "n": 66,
    "text": "Acute accidental exposure to chlorine fumes--a study of 82 cases. Moulick ND, Banavali S, Abhyankar AD, Borkar S, Aiyengar J, Kapadia NM, Khokhani RC. Indian J Chest Dis Allied Sci. 1992 Apr-Jun;34(2):85-9."
  },
  {
    "n": 67,
    "text": "Balloon mitral valvuloplasty in medically critically ill patients. Abhyankar AD, Damle AV, Agarwal A, Kaneria VK, Pahlajani DB, Mehta AB Indian Heart Journal 1992 : 44 ; 324. [Abstract]"
  },
  {
    "n": 68,
    "text": "Our experience with first fifty patient of percutaneous balloon mitral valvuloplasty by Inoue technique. Kaneria VK, Abhyankar AD, Kane GR, Damle AV, Pahlajani DB, Mehta AB. Indian Heart Journal 1992: 44; 324. [Abstract]"
  },
  {
    "n": 69,
    "text": "Coronary angiographic profile of patients with computerised treadmill positive only during recovery. Abhyankar AD, Agarwal A, Damle AV, Kaneria VK, Hiregouder NS, Pahlajani DB, Mehta AB. Indian Heart Journal 1992: 44; 273. [Abstract]"
  },
  {
    "n": 70,
    "text": "Atrial pacing stress echocardiography in assessment of coronary artery disease. Agarwal A, Abhyankar AD, Damle AV, Mehta AB, Pahlajani DB. Indian Heart Journal 1992:44; 302. [Abstract]"
  },
  {
    "n": 71,
    "text": "Hemodynamic response to intravenous disopyramide and verapamil in patients with hypertrophic cardiomyopathy. Abhyankar AD, Petkar SB, Punamiya KK, Kaneria VK, Pahlajani DB, Mehta AB. Indian Heart Journal 1992: 44; 291. [Abstract]"
  },
  {
    "n": 72,
    "text": "Comparison of percutaneous balloon mitral valvoplasty using Inoue balloon with surgical closed mitral commissurotomy using Tubb's dilator with surgical closed mitral commissurotomy using Inoue balloon- preliminary report. Abhyankar AD, Kaul A , Pahalajani DB, Chaukar A, Mehta AB. Indian Heart Journal 1992 :44 ;260. [Abstract]"
  },
  {
    "n": 73,
    "text": "Late potentials - current concepts. Verma VK, Abhyankar AD, Chonkar NS, Parikh JA. Indian Journal of Electrocardiology. Jan.1991; Vol 2:No.1, Pg 13."
  },
  {
    "n": 74,
    "text": "Wide QRS on exercise stress testing. Agarwal A, Parikh JA, Abhyankar AD, Vyas P, Athanikar N. Indian Journal of Electrocardiology. Jan.1991; Vol.2:No.1, Pg 19."
  },
  {
    "n": 75,
    "text": "Diagnosis of AMI in presence of conduction disturbances. Chonkar NS, Verma VK, Punamiya KK, Agarwal AG, Abhyankar AD. Indian journal of Electrocardiology. Jan 1991; vol.2:No.1, Pg 10."
  },
  {
    "n": 76,
    "text": "Angiographic Evaluation of Saphenous Vein Grafts. Abhyankar AD. Indian Heart Journal 1991. [Abstract]"
  },
  {
    "n": 77,
    "text": "Study of native circulation in patients following CABG. Abhyankar AD. Indian Heart Journal 1991. [Abstract]"
  },
  {
    "n": 78,
    "text": "Prognostic value of Programmed stimulation in patients following AMI. Abhyankar AD. Indian Heart Journal 1991. [Abstract]"
  },
  {
    "n": 79,
    "text": "Late potentials : Utility in arrhythmia prediction in post MI patients. Abhyankar AD. Indian Heart Journal 1991. [Abstract]"
  },
  {
    "n": 80,
    "text": "Balloon mitral valvuloplasty in patients with previous closed and open commissurotomy. Abhyankar AD. Indian Heart Journal 1991. [Abstract]"
  },
  {
    "n": 81,
    "text": "Electrophysiological study of patients with concealed bypass tract presenting with PSVT. Abhyankar AD. Indian Heart Journal 1991. [Abstract]"
  },
  {
    "n": 82,
    "text": "Study of electrophysiological properties of ventricle during programmed stimulation. Abhyankar AD. Indian Heart Journal 1991. [Abstract]"
  },
  {
    "n": 83,
    "text": "Semiquantitative assessment of Aortic regurgitation by colour doppler - comparison with angiocardiography. Abhyankar AD. Indian Heart Journal 1991. [Abstract]"
  },
  {
    "n": 84,
    "text": "Haemodynamic monitoring - When and what next? Abhyankar AD, Gandhi MJ. Postgraduate Clinics of APICON : 1990, Pg 22."
  },
  {
    "n": 85,
    "text": "Histopathological Characteristics in various cardiomyopathies by endomyocardial biopsy. Deshpande MA, Abhyankar AD, Chonkar NS, Parikh JA, Kane GR, Pandit SP, Gandhi MJ. Indian Heart Journal. 1990; 42, Pg 237 [Abstract]"
  },
  {
    "n": 86,
    "text": "PTCA in Cardiogenic Shock . Abhyankar AD, Parikh JA, Kane GR, Agarwal A, Patwardhan AM, Mehta AB, Gandhi MJ. Indian Heart Journal. 1990 : 42, Pg 267. [Abstract]"
  },
  {
    "n": 87,
    "text": "Acute Ventricular Septal Rupture. Verma VK, Abhyankar AD, Parikh JA, Kane GR, Gandhi MJ. Indian Heart Journal. 1990 : 42,Pg 301 [Abstract]"
  },
  {
    "n": 88,
    "text": "Type A lesion PTCA in our patient population. Parikh JA, Kane GR, Abhyankar AD, Kaneria VK, Verma VK, Chaukar AP, Gandhi MJ. Indian Heart Journal. 1990 :42,Pg 302 [Abstract]"
  },
  {
    "n": 89,
    "text": "Thrombolysis as an adjuvant to PTCA. Kane GR, Parikh JA, Abhyankar AD, Kaneria VK, Vyas P, Kaul AU, Gandhi MJ. Indian Heart Journal. 1990 :42, Pg 302 [Abstract ]"
  },
  {
    "n": 90,
    "text": "Torsade de pointes-an ECG discussion. Abhyankar AD, Parikh JA, Gandhi MJ. J Assoc Physicians India. 1989 Oct;37(10):653-4."
  },
  {
    "n": 91,
    "text": "Culprit vessel angioplasty in Unstable Angina. Parikh JA, Kane GR, Abhyankar AD, Gandhi MJ. Indian Heart Journal. 1989: 41, 362 [Abstract]."
  },
  {
    "n": 92,
    "text": "Thrombolytic therapy in unstable angina. Abhyankar AD, Kane GR, Parikh JA, Mehta AB, Gandhi MJ. Indian Heart journal. 1989, 41, Pg 363. [Abstract]"
  },
  {
    "n": 93,
    "text": "Coronary angiographic findings soon after non-Q wave MI. Parikh JA, Sharma P, Abhyankar AD, Gandhi MJ. Indian Heart Journal. 1989: 41,280-283."
  },
  {
    "n": 94,
    "text": "Six month follow-up of fourteen victims with short-term exposure to chlorine gas. Abhyankar AD, Bhambure N, Kamath NN, Pajankar SP, Nabar ST, Shrenivas A, Shah AC, Deshmukh SN. J Soc Occup Med. 1989 Winter;39(4):131-2."
  },
  {
    "n": 95,
    "text": "Vignettes in Electrocardiology - Bradycardia dependent block. Abhyankar AD, Chonkar NS, Gandhi MJ. Indian J. of Electrocardiology. 1988, Vol 1, Pg 31-32."
  },
  {
    "n": 96,
    "text": "Re-entry. Pahlajani DB, Parikh JA, Abhyankar AD. Indian J. of Electrocardiology. 1988 , Vol.1 Pg 20-23."
  },
  {
    "n": 97,
    "text": "Correlation of mitral valve area obtained by 2D Echo with intraoperative area. Abhyankar AD, Desai J, Parikh JA, Mehta AB, Pahlajani DB, Gandhi MJ. Indian Heart Journal. 1988, 40 : Pg 377. [Abstract ]"
  },
  {
    "n": 98,
    "text": "Ventriculoatrial shunt - an unusual cause of pulmonary hypertension. Kane GR, Parikh JA, Abhyankar AD, Gandhi MJ. Indian Heart Journal. 1988, 302 [ Abstract]"
  },
  {
    "n": 99,
    "text": "Electrolytes and the Heart. Abhyankar AD, Parikh JA. Indian Practitioner. November 1987, 40: 907-914."
  },
  {
    "n": 100,
    "text": "Rational therapy of Angina. Parikh JA, Abhyankar AD. Indian Practitioner. December 1987, 40: 1005-1012."
  },
  {
    "n": 101,
    "text": "Respiratory problems in Geriatrics. Abhyankar AD, Savargaonkar RS. Indian Practitioner. July 1986, Pg 619."
  },
  {
    "n": 102,
    "text": "Pulmonary functions and bronchoscopic evaluation of 62 patients of chlorine gas poisoning. Abhyankar AD. Journal of Asso. of Physicians of India; January1986. [Abstract]"
  }
]
