import type { Trial } from './types'

// Generated by scripts/extract-trials.mjs. Do not hand-edit.
export const trials: Trial[] = [
  {
    "molecule": "Rivaroxaban",
    "condition": "Non Valvular AF",
    "sponsor": "Bayer",
    "cro": "Quintiles"
  },
  {
    "molecule": "Rivaroxaban low Dose",
    "condition": "Heart Failure",
    "sponsor": "Sanofi",
    "cro": "Iqova"
  },
  {
    "molecule": "Sacubitril Valsartan",
    "condition": "Unstable Angina",
    "sponsor": "Pfizer",
    "cro": "ECCRI"
  },
  {
    "molecule": "Vaespladib",
    "condition": "Acute Coronary Syndrome",
    "sponsor": "Astra Zeneca",
    "cro": "Kendle"
  },
  {
    "molecule": "Sitaxentan",
    "condition": "ACS undergoing PCI",
    "sponsor": "Novartis",
    "cro": "Novo Nordisk"
  },
  {
    "molecule": "Canacunimab",
    "condition": "ACS post PCI",
    "sponsor": "Johnson & Johnson",
    "cro": "Paraxel"
  },
  {
    "molecule": "Ticagrelor",
    "condition": "Hypercholesterolemia",
    "sponsor": "Kova",
    "cro": "Batra Hospital & Research Centre"
  },
  {
    "molecule": "Prasugrel",
    "condition": "Stable CAD",
    "sponsor": "Anthera",
    "cro": "Max Neeman"
  },
  {
    "molecule": "Pemafibrate",
    "condition": "Primary Pulmonary Hypertension",
    "sponsor": "Novo Nordisk",
    "cro": "JSS"
  },
  {
    "molecule": "Bempedoic Acid",
    "condition": "Statin Intolerance",
    "sponsor": "Espirion",
    "cro": "SIRO"
  },
  {
    "molecule": "Semaglutide",
    "condition": "Familial Hypercholesterolemia",
    "sponsor": "Torrent",
    "cro": "Tech Observer"
  },
  {
    "molecule": "Alirocumab",
    "condition": "CAD with high BMI",
    "sponsor": "Actavis",
    "cro": "Pacific"
  },
  {
    "molecule": "Alogliptin",
    "condition": "CAD with Diabetes",
    "sponsor": "Terumo",
    "cro": "Trident"
  },
  {
    "molecule": "Thyroxin Analogue",
    "condition": "PCI with High Bleeding Risk",
    "sponsor": "Boston Scientific",
    "cro": "WCT"
  },
  {
    "molecule": "Long acting nitrate",
    "condition": "PCI in Diabetics",
    "sponsor": "Abbott",
    "cro": ""
  },
  {
    "molecule": "Otamixaban",
    "condition": "PCI in AMI",
    "sponsor": "Sahajanand Medical Technologies",
    "cro": ""
  },
  {
    "molecule": "Amlodipine",
    "condition": "Multivessel PCI",
    "sponsor": "Multivessel PCI",
    "cro": ""
  },
  {
    "molecule": "Irbesartan",
    "condition": "Hypertension",
    "sponsor": "Vascular Concepts",
    "cro": ""
  },
  {
    "molecule": "Ultimaster Stent",
    "condition": "Envision Scientific",
    "sponsor": "",
    "cro": ""
  },
  {
    "molecule": "Tetriflex/Tetrilimus Stent",
    "condition": "",
    "sponsor": "",
    "cro": ""
  },
  {
    "molecule": "Pronova Stent",
    "condition": "",
    "sponsor": "",
    "cro": ""
  },
  {
    "molecule": "Nostrum Stent",
    "condition": "",
    "sponsor": "",
    "cro": ""
  }
]
