import { readFileSync, writeFileSync } from 'node:fs'
import { parseHTML } from 'linkedom'

const src = readFileSync('scripts/source-pages/career-Hightlight.html', 'utf8')
const { document } = parseHTML(src)

// The trials table is the one whose rows mention molecules like "Rivaroxaban".
const table = [...document.querySelectorAll('table')].find(t =>
  /Rivaroxaban/i.test(t.textContent),
)
if (!table) throw new Error('could not locate the trials table')

const rows = [...table.querySelectorAll('tbody tr')]
  .map(tr => [...tr.querySelectorAll('td')].map(td => td.textContent.replace(/\s+/g, ' ').trim()))
  .filter(cells => cells.length >= 2 && cells[0] && !/^Trial Related/i.test(cells[0]))
  .map(([molecule, condition = '', sponsor = '', cro = '']) => ({
    molecule,
    condition,
    sponsor,
    cro,
  }))

if (rows.length < 15) throw new Error(`only found ${rows.length} trial rows`)

writeFileSync(
  'src/content/trials.ts',
  `import type { Trial } from './types'\n\n` +
    `// Generated by scripts/extract-trials.mjs — do not hand-edit.\n` +
    `export const trials: Trial[] = ${JSON.stringify(rows, null, 2)}\n`,
)
console.log(`wrote ${rows.length} trials`)
